name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_refined:
    name: Refined tests
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: 3.8.0
        poetry_version: 1.0
        args: install

    - name: Run pytest
      uses: abatilo/actions-poetry@v1.5.0
      env:
          TZ: America/New_York
      with:
        python_version: 3.8.0
        poetry_version: 1.0
        args: run python -m pytest -m refined
  test_unrefined:
    name: Unrefined tests
    runs-on: ubuntu-latest
    services:
      selenium-chrome:
        image: selenium/standalone-chrome:4.0.0-alpha-6-20200730
        volumes:
          - /dev/shm:/dev/shm
        ports:
          - 4444:4444
        env:
          TZ: America/New_York
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: 3.8.0
        poetry_version: 1.0
        args: install

    - name: is selenium server started?
      run: curl http://localhost:4444/status

    - name: Run pytest
      uses: abatilo/actions-poetry@v1.5.0
      env:
          SELENIUM_HOST: selenium-chrome
          SELENIUM_PORT: 4444
          TZ: America/New_York
      with:
        python_version: 3.8.0
        poetry_version: 1.0
        args: run python -m pytest -m unrefined
